version: "3.1"
services:
  database:
    restart: always
    image: postgres:13.2
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - sandbox_database_volume:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    expose:
      - "5433"
    networks:
      - back-end
  redis:
    image: redis
    networks:
      - back-end
    expose:
      - "6379"
  api:
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile
    expose:
      - "5000"
    image: ethsign-api
    volumes:
      - .:/ethsign-api
      - backend_static_volume:/ethsigns-app/app/static/
    entrypoint: ["/bin/bash", "-c", "/ethsigns-app/docker/start_app.sh"]
    depends_on:
      - redis
      - database
    stdin_open: true
    tty: true
    environment:
      - FLASK_APP=${FLASK_APP}
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@database:5432/${DB_NAME}
      - FLASK_ENV=${FLASK_ENV}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - SQLALCHEMY_TRACK_MODIFICATIONS=${SQLALCHEMY_TRACK_MODIFICATIONS}

      - CELERY_BROKER_URL=redis://redis
      - CELERY_RESULT_BACKEND=redis://redis
      - REDIS_URL=redis://redis
      - RPC_URL=${RPC_URL}
      - CONTRACT_ADDRESS=${CONTRACT_ADDRESS}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - IPFS_GATEWAY_URL=${IPFS_GATEWAY_URL}
      - IPFS_API_KEY=${IPFS_API_KEY}
      - IPFS_URL=${IPFS_URL}
      - MINTING_FEE=${MINTING_FEE}
      - MAX_TOKEN_COUNT=${MAX_TOKEN_COUNT}
    networks:
      - back-end
      - front-end

  web:
    restart: always
    ports:
      - "80:80"
      - "443:443"
    image: ethsigns-web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # - /etc/letsencrypt/:/etc/letsencrypt/
    networks:
      - back-end
      - front-end
    depends_on:
      - api

networks:
  back-end:
  front-end:
volumes:
  backend_static_volume:
  sandbox_database_volume:
